### Pandas Basics

Pandas is an open source data analysis library written in python

It uses the power and speed of numpy to make data manipulation and analysis easy for data scientists

It's key data structure is called DataFrame

we can a
nalyse :
1)---> 1d , and it is similary like numpy 1d arrays series  
2) ---> 2d , tabular format ---> rows and column  dataframe

In [13]:
# pip install pandas
import pandas as pd

In [14]:
# checking version of pandas
print(pd.__version__)

2.1.4

### Pandas Data Structures
1) **series ----> 1D array**
   1) Definition : A pandas series is a 1D array like object that can hold different data types     elements. It is similar to a column in DataFrame.
   2) Homogeneity: All elements in a Series must be of the same data type.
3) **Data Frame ----> 2D array**
   1) Definition: A DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).
   2) Rows and Columns: Consists of rows and columns, each column being a Series. Columns can be of different data types.

In [15]:
import numpy as np
arr = np.array([1,2,3,4,5,6.6])
arr.dtype
print(arr)

[1.  2.  3.  4.  5.  6.6]

#### series creation ---> list , tuple , dictionary , numpy arrays

In [16]:
# using list
print(pd.Series([2,3,4,5,6]))

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [17]:
print(pd.Series(["indore","bhopal"]))

0    indore
1    bhopal
dtype: object

In [18]:
# tuple
print(pd.Series((2,3,4,5,6)))

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [19]:
# dictionary
print(pd.Series({"city":"delhi",'price':500}))

city     delhi
price      500
dtype: object

In [20]:
import numpy as np
arr = np.array([30,40,50,60,70])
print(pd.Series(arr))

0    30
1    40
2    50
3    60
4    70
dtype: int32

In [21]:
# changing index label
data = pd.Series([2,3,4,5,6],index=[2,5,3,4,1])
data

2    2
5    3
3    4
4    5
1    6
dtype: int64

In [22]:
data = pd.Series([2,3,4,5,6],index=[2,5,3,4,1])
data.sort_index(ascending=False)

5    3
4    5
3    4
2    2
1    6
dtype: int64

In [23]:
data.sort_values(ascending=False)

1    6
4    5
3    4
5    3
2    2
dtype: int64

In [24]:
data = pd.Series([2,3,4,5,6],index=['a','c','d','b','e'])
data

a    2
c    3
d    4
b    5
e    6
dtype: int64

In [25]:
data.sort_index(ascending=True)

a    2
b    5
c    3
d    4
e    6
dtype: int64

In [26]:
data.index

Index(['a', 'c', 'd', 'b', 'e'], dtype='object')

In [27]:
data.values

array([2, 3, 4, 5, 6], dtype=int64)

In [28]:
data.value_counts

<bound method IndexOpsMixin.value_counts of a    2
c    3
d    4
b    5
e    6
dtype: int64>

In [29]:
for labels in data.index:
    print(labels,data[labels])

a 2
c 3
d 4
b 5
e 6

In [30]:
# merging series
d1 = pd.Series([3,4,5,6,7])
d2 = pd.Series([5,6,7,8,9])
d3 = pd.concat([d1,d2])
d3

0    3
1    4
2    5
3    6
4    7
0    5
1    6
2    7
3    8
4    9
dtype: int64

In [31]:
d3.reset_index(drop=True)

0    3
1    4
2    5
3    6
4    7
5    5
6    6
7    7
8    8
9    9
dtype: int64

#### indexing and slicing in series

In [32]:
data = pd.Series([2,3,4,5,6],index=['a','c','d','b','e'])
data

a    2
c    3
d    4
b    5
e    6
dtype: int64

In [33]:
# reguler scling approach
print(data[1]) # indexing
print(data['d']) # indexing
print(data[['a','b']]) # indexing 
print(data['a':'b']) # scling

3
4
a    2
b    5
dtype: int64
a    2
c    3
d    4
b    5
dtype: int64

C:\Users\HIMANSHU SURYAVANSHI\AppData\Local\Temp\ipykernel_17672\3738166335.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(data[1]) # indexing

In [34]:
# label based indexing/slcing --> loc[]
# positional indexing/slcing --> iloc[]

In [35]:
data = pd.Series([2,3,4,5,6],index=['a','c','d','b','e'])
data

a    2
c    3
d    4
b    5
e    6
dtype: int64

In [36]:
print(data['c'])
print(data.loc['d'])
print(data.iloc[4])

3
4
6

In [37]:
print(data.loc['a':'b'])

a    2
c    3
d    4
b    5
dtype: int64

In [38]:
print(data.iloc[1:4])

c    3
d    4
b    5
dtype: int64

### methods in Pandas Series

In [39]:
import pandas as pd
df = pd.Series([20,30,40,50,60],index=['a','b','c','d','e'])
df

a    20
b    30
c    40
d    50
e    60
dtype: int64

In [40]:
# methods
print(df.sum())
print(df.mean())
print(df.median())
print(df.max())
print(df.min())

200
40.0
40.0
60
20

In [41]:
# elementwise
df = df.map(lambda x : x*2)
df

a     40
b     60
c     80
d    100
e    120
dtype: int64

In [42]:
# filter
filtered = df.where(df>60)
filtered

a      NaN
b      NaN
c     80.0
d    100.0
e    120.0
dtype: float64

In [43]:
filtered.dropna()

c     80.0
d    100.0
e    120.0
dtype: float64

In [44]:
filtered.fillna(0)

a      0.0
b      0.0
c     80.0
d    100.0
e    120.0
dtype: float64

In [45]:
df.describe()

count      5.000000
mean      80.000000
std       31.622777
min       40.000000
25%       60.000000
50%       80.000000
75%      100.000000
max      120.000000
dtype: float64

### DataFrame

In [46]:
# creating dataframe
import pandas as pd
df = pd.DataFrame({
    'Name':['Salman','Arbaz','Sohail','Neil','Nitin'],
    'Age':[50,60,40,20,30],
    'City':['Indore','Bhopal','Mumbai','chennai',"Delhi"]
})
df

     Name  Age     City
0  Salman   50   Indore
1   Arbaz   60   Bhopal
2  Sohail   40   Mumbai
3    Neil   20  chennai
4   Nitin   30    Delhi

### column operation

In [47]:
import numpy as np
np.random.seed(2)
arr = np.random.randint(1,20,(4,3))
df = pd.DataFrame(arr,columns=['Age',"Weight",'Height'])
df

   Age  Weight  Height
0    9      16      14
1    9      12      19
2   12       9       8
3    3      18      12

In [48]:
df.columns

Index(['Age', 'Weight', 'Height'], dtype='object')

In [49]:
df.values

array([[ 9, 16, 14],
       [ 9, 12, 19],
       [12,  9,  8],
       [ 3, 18, 12]])

In [50]:
df.columns = ('age','weight','height') # changing all the columns at once

In [51]:
df

   age  weight  height
0    9      16      14
1    9      12      19
2   12       9       8
3    3      18      12

In [52]:
df = df.rename(columns={'age':'Age'})
df

   Age  weight  height
0    9      16      14
1    9      12      19
2   12       9       8
3    3      18      12

In [53]:
df.shape

(4, 3)

In [54]:
df.ndim

2

In [55]:
df.columns

Index(['Age', 'weight', 'height'], dtype='object')

In [56]:
df.values

array([[ 9, 16, 14],
       [ 9, 12, 19],
       [12,  9,  8],
       [ 3, 18, 12]])

In [57]:
# adding single column
df['Department'] = ['IT',"Sales","HR","Healthcare"]
df

   Age  weight  height  Department
0    9      16      14          IT
1    9      12      19       Sales
2   12       9       8          HR
3    3      18      12  Healthcare

In [58]:
# adding multiple columns
df = df.assign(name=['Salman','Arbaz','Sohail','Neil'],
         income=[4000,5000,6000,70000])
df

   Age  weight  height  Department    name  income
0    9      16      14          IT  Salman    4000
1    9      12      19       Sales   Arbaz    5000
2   12       9       8          HR  Sohail    6000
3    3      18      12  Healthcare    Neil   70000

In [59]:
df.columns

Index(['Age', 'weight', 'height', 'Department', 'name', 'income'], dtype='object')

In [60]:
df = df.reindex(columns=['name','Age', 'weight', 'height', 'Department', 'income']) # column shuffling
df

     name  Age  weight  height  Department  income
0  Salman    9      16      14          IT    4000
1   Arbaz    9      12      19       Sales    5000
2  Sohail   12       9       8          HR    6000
3    Neil    3      18      12  Healthcare   70000

In [61]:
df = df.set_index('name')
df

        Age  weight  height  Department  income
name
Salman    9      16      14          IT    4000
Arbaz     9      12      19       Sales    5000
Sohail   12       9       8          HR    6000
Neil      3      18      12  Healthcare   70000

In [62]:
df = df.reset_index()
df

     name  Age  weight  height  Department  income
0  Salman    9      16      14          IT    4000
1   Arbaz    9      12      19       Sales    5000
2  Sohail   12       9       8          HR    6000
3    Neil    3      18      12  Healthcare   70000

In [63]:
# droping columns
df.drop(columns=['weight'])

     name  Age  height  Department  income
0  Salman    9      14          IT    4000
1   Arbaz    9      19       Sales    5000
2  Sohail   12       8          HR    6000
3    Neil    3      12  Healthcare   70000

In [64]:
df.describe()

             Age     weight     height        income
count   4.000000   4.000000   4.000000      4.000000
mean    8.250000  13.750000  13.250000  21250.000000
std     3.774917   4.031129   4.573474  32510.254792
min     3.000000   9.000000   8.000000   4000.000000
25%     7.500000  11.250000  11.000000   4750.000000
50%     9.000000  14.000000  13.000000   5500.000000
75%     9.750000  16.500000  15.250000  22000.000000
max    12.000000  18.000000  19.000000  70000.000000

In [65]:
df.head(2)

     name  Age  weight  height Department  income
0  Salman    9      16      14         IT    4000
1   Arbaz    9      12      19      Sales    5000

In [66]:
df.tail(2)

     name  Age  weight  height  Department  income
2  Sohail   12       9       8          HR    6000
3    Neil    3      18      12  Healthcare   70000

In [67]:
df

     name  Age  weight  height  Department  income
0  Salman    9      16      14          IT    4000
1   Arbaz    9      12      19       Sales    5000
2  Sohail   12       9       8          HR    6000
3    Neil    3      18      12  Healthcare   70000

In [68]:
# date 31-07

In [69]:
df.Age

0     9
1     9
2    12
3     3
Name: Age, dtype: int32

In [70]:
df['Age']

0     9
1     9
2    12
3     3
Name: Age, dtype: int32

### Rows operation

In [71]:
df1 = df
df1

     name  Age  weight  height  Department  income
0  Salman    9      16      14          IT    4000
1   Arbaz    9      12      19       Sales    5000
2  Sohail   12       9       8          HR    6000
3    Neil    3      18      12  Healthcare   70000

In [72]:
df1.head(3) # checking top n rows

     name  Age  weight  height Department  income
0  Salman    9      16      14         IT    4000
1   Arbaz    9      12      19      Sales    5000
2  Sohail   12       9       8         HR    6000

In [73]:
df1.tail(3) # checking bottom n rows

     name  Age  weight  height  Department  income
1   Arbaz    9      12      19       Sales    5000
2  Sohail   12       9       8          HR    6000
3    Neil    3      18      12  Healthcare   70000

In [74]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   Age         4 non-null      int32
 2   weight      4 non-null      int32
 3   height      4 non-null      int32
 4   Department  4 non-null      object
 5   income      4 non-null      int64
dtypes: int32(3), int64(1), object(2)
memory usage: 276.0+ bytes

In [75]:
# adding single row
df1.loc[4] = ['SUbham',25,75,64,"Sales",7000]
df1

     name  Age  weight  height  Department  income
0  Salman    9      16      14          IT    4000
1   Arbaz    9      12      19       Sales    5000
2  Sohail   12       9       8          HR    6000
3    Neil    3      18      12  Healthcare   70000
4  SUbham   25      75      64       Sales    7000

In [76]:
new_rows = [
    ['Sakshi',27,80,64,"Auto",7000],
    ['roahan',25,77,64,"Hr",9000],
    ['priyashu',30,60,64,"IT",10000]
]

In [77]:
# adding multiple row
new_df = pd.DataFrame(new_rows,columns=df1.columns)
new_df

       name  Age  weight  height Department  income
0    Sakshi   27      80      64       Auto    7000
1    roahan   25      77      64         Hr    9000
2  priyashu   30      60      64         IT   10000

#### merging Dataframe

In [78]:
df1 = pd.concat([df1,new_df],ignore_index=True)

df1

       name  Age  weight  height  Department  income
0    Salman    9      16      14          IT    4000
1     Arbaz    9      12      19       Sales    5000
2    Sohail   12       9       8          HR    6000
3      Neil    3      18      12  Healthcare   70000
4    SUbham   25      75      64       Sales    7000
5    Sakshi   27      80      64        Auto    7000
6    roahan   25      77      64          Hr    9000
7  priyashu   30      60      64          IT   10000

### updating values

In [79]:
df1['Age']

0     9
1     9
2    12
3     3
4    25
5    27
6    25
7    30
Name: Age, dtype: int64

In [80]:
df1['Age'][1] = 45

C:\Users\HIMANSHU SURYAVANSHI\AppData\Local\Temp\ipykernel_17672\24271671.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Age'][1] = 45

In [81]:
df1

       name  Age  weight  height  Department  income
0    Salman    9      16      14          IT    4000
1     Arbaz   45      12      19       Sales    5000
2    Sohail   12       9       8          HR    6000
3      Neil    3      18      12  Healthcare   70000
4    SUbham   25      75      64       Sales    7000
5    Sakshi   27      80      64        Auto    7000
6    roahan   25      77      64          Hr    9000
7  priyashu   30      60      64          IT   10000

In [82]:
df1['Department'][5] = 'Automotive'

C:\Users\HIMANSHU SURYAVANSHI\AppData\Local\Temp\ipykernel_17672\1501192777.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Department'][5] = 'Automotive'

In [83]:
df1

       name  Age  weight  height  Department  income
0    Salman    9      16      14          IT    4000
1     Arbaz   45      12      19       Sales    5000
2    Sohail   12       9       8          HR    6000
3      Neil    3      18      12  Healthcare   70000
4    SUbham   25      75      64       Sales    7000
5    Sakshi   27      80      64  Automotive    7000
6    roahan   25      77      64          Hr    9000
7  priyashu   30      60      64          IT   10000

In [84]:
# updating multiple values
df1['Department'] = df1['Department'].replace({
    'IT':"Information Technology",
    'HR':"Human Resource",
    'Hr':'Human Resource'
})
df1

       name  Age  weight  height              Department  income
0    Salman    9      16      14  Information Technology    4000
1     Arbaz   45      12      19                   Sales    5000
2    Sohail   12       9       8          Human Resource    6000
3      Neil    3      18      12              Healthcare   70000
4    SUbham   25      75      64                   Sales    7000
5    Sakshi   27      80      64              Automotive    7000
6    roahan   25      77      64          Human Resource    9000
7  priyashu   30      60      64  Information Technology   10000

### Filtering

In [85]:
# boolean indexing
df1[df1['Age']>20]

       name  Age  weight  height              Department  income
1     Arbaz   45      12      19                   Sales    5000
4    SUbham   25      75      64                   Sales    7000
5    Sakshi   27      80      64              Automotive    7000
6    roahan   25      77      64          Human Resource    9000
7  priyashu   30      60      64  Information Technology   10000

In [86]:
df1[df1['Department']=='Information Technology']

       name  Age  weight  height              Department  income
0    Salman    9      16      14  Information Technology    4000
7  priyashu   30      60      64  Information Technology   10000

In [87]:
# filtering the data using multiple condition with logical condition (&--> bitwise and , |--> bitwise or , ~ --> bitwise not) 
df1[(df1['Age']>20) & (df1['Department']=='Sales')]

     name  Age  weight  height Department  income
1   Arbaz   45      12      19      Sales    5000
4  SUbham   25      75      64      Sales    7000

In [88]:
df1[(df1['Age']==25) & (df1['Department']=='Sales')]

     name  Age  weight  height Department  income
4  SUbham   25      75      64      Sales    7000

In [89]:
df1[~((df1['Age']==25) & (df1['Department']=='Sales'))]

       name  Age  weight  height              Department  income
0    Salman    9      16      14  Information Technology    4000
1     Arbaz   45      12      19                   Sales    5000
2    Sohail   12       9       8          Human Resource    6000
3      Neil    3      18      12              Healthcare   70000
5    Sakshi   27      80      64              Automotive    7000
6    roahan   25      77      64          Human Resource    9000
7  priyashu   30      60      64  Information Technology   10000

In [90]:
df1[~((df1['Age']==25) | (df1['Department']=='Sales'))]

       name  Age  weight  height              Department  income
0    Salman    9      16      14  Information Technology    4000
2    Sohail   12       9       8          Human Resource    6000
3      Neil    3      18      12              Healthcare   70000
5    Sakshi   27      80      64              Automotive    7000
7  priyashu   30      60      64  Information Technology   10000

In [91]:
# 01-august

##### loc and iloc method

In [92]:
df1

       name  Age  weight  height              Department  income
0    Salman    9      16      14  Information Technology    4000
1     Arbaz   45      12      19                   Sales    5000
2    Sohail   12       9       8          Human Resource    6000
3      Neil    3      18      12              Healthcare   70000
4    SUbham   25      75      64                   Sales    7000
5    Sakshi   27      80      64              Automotive    7000
6    roahan   25      77      64          Human Resource    9000
7  priyashu   30      60      64  Information Technology   10000

In [93]:
df1.loc[0]

name                          Salman
Age                                9
weight                            16
height                            14
Department    Information Technology
income                          4000
Name: 0, dtype: object

In [94]:
df1.loc[[0,5]]

     name  Age  weight  height              Department  income
0  Salman    9      16      14  Information Technology    4000
5  Sakshi   27      80      64              Automotive    7000

In [95]:
df1.loc[[0,5],'name']

0    Salman
5    Sakshi
Name: name, dtype: object

In [96]:
df1.loc[[0,5],['name','Department']] # indexing

     name              Department
0  Salman  Information Technology
5  Sakshi              Automotive

In [97]:
df1.loc[0:5,['name','Department']] # slicing

     name              Department
0  Salman  Information Technology
1   Arbaz                   Sales
2  Sohail          Human Resource
3    Neil              Healthcare
4  SUbham                   Sales
5  Sakshi              Automotive

In [98]:
df1.loc[0:5,'name':'Department'] # slicing

     name  Age  weight  height              Department
0  Salman    9      16      14  Information Technology
1   Arbaz   45      12      19                   Sales
2  Sohail   12       9       8          Human Resource
3    Neil    3      18      12              Healthcare
4  SUbham   25      75      64                   Sales
5  Sakshi   27      80      64              Automotive

##### iloc method

In [99]:
df1.iloc[0]

name                          Salman
Age                                9
weight                            16
height                            14
Department    Information Technology
income                          4000
Name: 0, dtype: object

In [100]:
df1.iloc[[0,5],[0,4]]

     name              Department
0  Salman  Information Technology
5  Sakshi              Automotive

In [101]:
df1.iloc[0:5,[0,4]]

     name              Department
0  Salman  Information Technology
1   Arbaz                   Sales
2  Sohail          Human Resource
3    Neil              Healthcare
4  SUbham                   Sales

In [102]:
df1.iloc[0:6,0:5]

     name  Age  weight  height              Department
0  Salman    9      16      14  Information Technology
1   Arbaz   45      12      19                   Sales
2  Sohail   12       9       8          Human Resource
3    Neil    3      18      12              Healthcare
4  SUbham   25      75      64                   Sales
5  Sakshi   27      80      64              Automotive

##### filtering columns with filter() and regex

In [103]:
df1.filter(regex='a')

       name              Department
0    Salman  Information Technology
1     Arbaz                   Sales
2    Sohail          Human Resource
3      Neil              Healthcare
4    SUbham                   Sales
5    Sakshi              Automotive
6    roahan          Human Resource
7  priyashu  Information Technology

In [104]:
df1.filter(regex='^D') # starting letter

               Department
0  Information Technology
1                   Sales
2          Human Resource
3              Healthcare
4                   Sales
5              Automotive
6          Human Resource
7  Information Technology

In [105]:
df1.filter(regex='t$')

   weight  height              Department
0      16      14  Information Technology
1      12      19                   Sales
2       9       8          Human Resource
3      18      12              Healthcare
4      75      64                   Sales
5      80      64              Automotive
6      77      64          Human Resource
7      60      64  Information Technology

In [106]:
df1.filter(regex='.+e.+')

   weight  height              Department
0      16      14  Information Technology
1      12      19                   Sales
2       9       8          Human Resource
3      18      12              Healthcare
4      75      64                   Sales
5      80      64              Automotive
6      77      64          Human Resource
7      60      64  Information Technology

##### filtering rows

In [107]:
df1[df1['Age']>20]

       name  Age  weight  height              Department  income
1     Arbaz   45      12      19                   Sales    5000
4    SUbham   25      75      64                   Sales    7000
5    Sakshi   27      80      64              Automotive    7000
6    roahan   25      77      64          Human Resource    9000
7  priyashu   30      60      64  Information Technology   10000

In [108]:
df1[df1['name'].str.contains('S',case=True,regex=True)] # bas esme s hona chahiye

     name  Age  weight  height              Department  income
0  Salman    9      16      14  Information Technology    4000
2  Sohail   12       9       8          Human Resource    6000
4  SUbham   25      75      64                   Sales    7000
5  Sakshi   27      80      64              Automotive    7000

In [109]:
df1[df1['name'].str.contains('^R',case=False,regex=True)]

     name  Age  weight  height      Department  income
6  roahan   25      77      64  Human Resource    9000

In [110]:
df1[df1['name'].str.contains('^S',case=True,regex=True)]

     name  Age  weight  height              Department  income
0  Salman    9      16      14  Information Technology    4000
2  Sohail   12       9       8          Human Resource    6000
4  SUbham   25      75      64                   Sales    7000
5  Sakshi   27      80      64              Automotive    7000

In [111]:
df1[df1['name'].str.contains('u$',case=False,regex=True)] # bas esme s hona chahiye

       name  Age  weight  height              Department  income
7  priyashu   30      60      64  Information Technology   10000

In [112]:
# for department
df1[df1['Department'].str.contains('.+T.+',case=True,regex=True)] # bas esme s hona chahiye

       name  Age  weight  height              Department  income
0    Salman    9      16      14  Information Technology    4000
7  priyashu   30      60      64  Information Technology   10000

#### sorting

In [113]:
df1.sort_values('Age',ascending=False)

       name  Age  weight  height              Department  income
1     Arbaz   45      12      19                   Sales    5000
7  priyashu   30      60      64  Information Technology   10000
5    Sakshi   27      80      64              Automotive    7000
4    SUbham   25      75      64                   Sales    7000
6    roahan   25      77      64          Human Resource    9000
2    Sohail   12       9       8          Human Resource    6000
0    Salman    9      16      14  Information Technology    4000
3      Neil    3      18      12              Healthcare   70000

In [114]:
df1.sort_values('name',ascending=True) # problem

       name  Age  weight  height              Department  income
1     Arbaz   45      12      19                   Sales    5000
3      Neil    3      18      12              Healthcare   70000
4    SUbham   25      75      64                   Sales    7000
5    Sakshi   27      80      64              Automotive    7000
0    Salman    9      16      14  Information Technology    4000
2    Sohail   12       9       8          Human Resource    6000
7  priyashu   30      60      64  Information Technology   10000
6    roahan   25      77      64          Human Resource    9000

In [115]:
df1.sort_values('name',key=lambda x : x.str.upper(),ascending=True) # solution

       name  Age  weight  height              Department  income
1     Arbaz   45      12      19                   Sales    5000
3      Neil    3      18      12              Healthcare   70000
7  priyashu   30      60      64  Information Technology   10000
6    roahan   25      77      64          Human Resource    9000
5    Sakshi   27      80      64              Automotive    7000
0    Salman    9      16      14  Information Technology    4000
2    Sohail   12       9       8          Human Resource    6000
4    SUbham   25      75      64                   Sales    7000

In [116]:
# 02-august

In [117]:
df1['Age'].nlargest(2) # extract top n ages

1    45
7    30
Name: Age, dtype: int64

In [118]:
df1['Age'].nsmallest(2) # extract top n ages

3    3
0    9
Name: Age, dtype: int64

### N largest or n smallest salary

In [119]:
import pandas as pd

# Data
emps = [
    {"salary": 10000, "emp_id": 1},
    {"salary": 12000, "emp_id": 2},
    {"salary": 13000, "emp_id": 3},
    {"salary": 14000, "emp_id": 4}
]

# Create DataFrame
df = pd.DataFrame(emps)
df

   salary  emp_id
0   10000       1
1   12000       2
2   13000       3
3   14000       4

In [120]:
# Find the employee ID with the second largest salary
second_largest_salary_emp_id = df['emp_id'].nlargest(2).iloc[-1]

print(second_largest_salary_emp_id)

3

In [121]:
# Find  the second largest salary
second_largest_salary = df['salary'].nlargest(2).iloc[-1]

print(second_largest_salary)

13000

##### aggregate functions

In [122]:
df1.count()

name          8
Age           8
weight        8
height        8
Department    8
income        8
dtype: int64

In [123]:
df1["Department"].value_counts()

Department
Information Technology    2
Sales                     2
Human Resource            2
Healthcare                1
Automotive                1
Name: count, dtype: int64

In [124]:
df1.max()

name          roahan
Age               45
weight            80
height            64
Department     Sales
income         70000
dtype: object

In [125]:
print(df1['Age'].sum())
print(df1['Age'].min())
print(df1['Age'].max())
print(df1['Age'].std())
print(df1['Age'].var())
print(df1['Age'].mean())

176
3
45
13.44831375515692
180.85714285714286
22.0

#### Group by

In [126]:
df1

       name  Age  weight  height              Department  income
0    Salman    9      16      14  Information Technology    4000
1     Arbaz   45      12      19                   Sales    5000
2    Sohail   12       9       8          Human Resource    6000
3      Neil    3      18      12              Healthcare   70000
4    SUbham   25      75      64                   Sales    7000
5    Sakshi   27      80      64              Automotive    7000
6    roahan   25      77      64          Human Resource    9000
7  priyashu   30      60      64  Information Technology   10000

In [127]:
# find the total income department wise
df1.groupby('Department')['income'].sum()

Department
Automotive                 7000
Healthcare                70000
Human Resource            15000
Information Technology    14000
Sales                     12000
Name: income, dtype: int64

In [128]:
# find the empoloyee count departmentwise
df1.groupby('Department')['name'].count()

Department
Automotive                1
Healthcare                1
Human Resource            2
Information Technology    2
Sales                     2
Name: name, dtype: int64

In [129]:
df1.groupby('Department')[['income','weight']].sum()

                        income  weight
Department
Automotive                7000      80
Healthcare               70000      18
Human Resource           15000      86
Information Technology   14000      76
Sales                    12000      87

In [130]:
df1.groupby(['Department','name'])['income'].sum()

Department              name
Automotive              Sakshi       7000
Healthcare              Neil        70000
Human Resource          Sohail       6000
                        roahan       9000
Information Technology  Salman       4000
                        priyashu    10000
Sales                   Arbaz        5000
                        SUbham       7000
Name: income, dtype: int64

In [131]:
df1.groupby('Department')['income'].agg(['sum','max','min'])

                          sum    max    min
Department
Automotive               7000   7000   7000
Healthcare              70000  70000  70000
Human Resource          15000   9000   6000
Information Technology  14000  10000   4000
Sales                   12000   7000   5000

In [132]:
df1

       name  Age  weight  height              Department  income
0    Salman    9      16      14  Information Technology    4000
1     Arbaz   45      12      19                   Sales    5000
2    Sohail   12       9       8          Human Resource    6000
3      Neil    3      18      12              Healthcare   70000
4    SUbham   25      75      64                   Sales    7000
5    Sakshi   27      80      64              Automotive    7000
6    roahan   25      77      64          Human Resource    9000
7  priyashu   30      60      64  Information Technology   10000

In [133]:
df1.groupby('Department').aggregate({'income':'max','Age':'min'})

                        income  Age
Department
Automotive                7000   27
Healthcare               70000    3
Human Resource            9000   12
Information Technology   10000    9
Sales                     7000   25

In [134]:
df1.groupby('Department').aggregate({'income':'max','name':'min'})

                        income    name
Department
Automotive                7000  Sakshi
Healthcare               70000    Neil
Human Resource            9000  Sohail
Information Technology   10000  Salman
Sales                     7000   Arbaz

### Handling missing values

In [135]:

import pandas as pd

# Data for the DataFrame
data = {
    'name': ['Salman', 'Arbaz', 'Sohail', 'Neil', 'SUbham', 'Sakshi', 'roahan', 'priyashu'],
    'Age': [None, 45, 12, None, 25, 27, 25, 30],
    'weight': [16, None, 9, 18, 75, 80, None, 60],
    'height': [14, 19, None, 12, 64, None, 64, 64],
    'Department': ['Information Technology', 'Sales', 'Human Resource', 'Healthcare', 'Sales', 'Automotive', 'Human Resource', 'Information Technology'],
    'income': [4000, 5000, 6000, 70000, 7000, 7000, 9000, 10000],
    'country': ['India', 'USA', 'China', 'India', 'China', 'Japan', 'India', 'Shrilanka'],
    'city': ['Indore', 'Los Angeles', 'Wuhan', 'Banglore', 'Bijing', 'Tokyo', 'Indore', 'Colambo']
}

df = pd.DataFrame(data)

df

,name,Age,weight,height,Department,income,country,city
0,Salman,NaN,16.0,14.0,Information Technology,4000,India,Indore
1,Arbaz,45.0,NaN,19.0,Sales,5000,USA,Los Angeles
2,Sohail,12.0,9.0,NaN,Human Resource,6000,China,Wuhan
3,Neil,NaN,18.0,12.0,Healthcare,70000,India,Banglore
4,SUbham,25.0,75.0,64.0,Sales,7000,China,Bijing
5,Sakshi,27.0,80.0,NaN,Automotive,7000,Japan,Tokyo
6,roahan,25.0,NaN,64.0,Human Resource,9000,India,Indore
7,priyashu,30.0,60.0,64.0,Information Technology,10000,Shrilanka,Colambo

In [136]:
# checking null values
df.isna().sum()

name          0
Age           2
weight        2
height        2
Department    0
income        0
country       0
city          0
dtype: int64

In [137]:
df.isnull().sum()

name          0
Age           2
weight        2
height        2
Department    0
income        0
country       0
city          0
dtype: int64

In [138]:
# droping the rows that contains null values
df.dropna()

,name,Age,weight,height,Department,income,country,city
4,SUbham,25.0,75.0,64.0,Sales,7000,China,Bijing
7,priyashu,30.0,60.0,64.0,Information Technology,10000,Shrilanka,Colambo

In [139]:
df.dropna(axis=1) # droping column havng null values

       name              Department  income    country         city
0    Salman  Information Technology    4000      India       Indore
1     Arbaz                   Sales    5000        USA  Los Angeles
2    Sohail          Human Resource    6000      China        Wuhan
3      Neil              Healthcare   70000      India     Banglore
4    SUbham                   Sales    7000      China       Bijing
5    Sakshi              Automotive    7000      Japan        Tokyo
6    roahan          Human Resource    9000      India       Indore
7  priyashu  Information Technology   10000  Shrilanka      Colambo

In [140]:
# filling null values
df.fillna(0)

,name,Age,weight,height,Department,income,country,city
0,Salman,0.0,16.0,14.0,Information Technology,4000,India,Indore
1,Arbaz,45.0,0.0,19.0,Sales,5000,USA,Los Angeles
2,Sohail,12.0,9.0,0.0,Human Resource,6000,China,Wuhan
3,Neil,0.0,18.0,12.0,Healthcare,70000,India,Banglore
4,SUbham,25.0,75.0,64.0,Sales,7000,China,Bijing
5,Sakshi,27.0,80.0,0.0,Automotive,7000,Japan,Tokyo
6,roahan,25.0,0.0,64.0,Human Resource,9000,India,Indore
7,priyashu,30.0,60.0,64.0,Information Technology,10000,Shrilanka,Colambo

In [141]:
df = df.fillna(df['Age'].mean()) # homework
df

,name,Age,weight,height,Department,income,country,city
0,Salman,27.333333,16.000000,14.000000,Information Technology,4000,India,Indore
1,Arbaz,45.000000,27.333333,19.000000,Sales,5000,USA,Los Angeles
2,Sohail,12.000000,9.000000,27.333333,Human Resource,6000,China,Wuhan
3,Neil,27.333333,18.000000,12.000000,Healthcare,70000,India,Banglore
4,SUbham,25.000000,75.000000,64.000000,Sales,7000,China,Bijing
5,Sakshi,27.000000,80.000000,27.333333,Automotive,7000,Japan,Tokyo
6,roahan,25.000000,27.333333,64.000000,Human Resource,9000,India,Indore
7,priyashu,30.000000,60.000000,64.000000,Information Technology,10000,Shrilanka,Colambo

In [142]:
df.isna().sum()

name          0
Age           0
weight        0
height        0
Department    0
income        0
country       0
city          0
dtype: int64

#### datatype conversion

In [143]:
df

,name,Age,weight,height,Department,income,country,city
0,Salman,27.333333,16.000000,14.000000,Information Technology,4000,India,Indore
1,Arbaz,45.000000,27.333333,19.000000,Sales,5000,USA,Los Angeles
2,Sohail,12.000000,9.000000,27.333333,Human Resource,6000,China,Wuhan
3,Neil,27.333333,18.000000,12.000000,Healthcare,70000,India,Banglore
4,SUbham,25.000000,75.000000,64.000000,Sales,7000,China,Bijing
5,Sakshi,27.000000,80.000000,27.333333,Automotive,7000,Japan,Tokyo
6,roahan,25.000000,27.333333,64.000000,Human Resource,9000,India,Indore
7,priyashu,30.000000,60.000000,64.000000,Information Technology,10000,Shrilanka,Colambo

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        8 non-null      object
 1   Age         8 non-null      float64
 2   weight      8 non-null      float64
 3   height      8 non-null      float64
 4   Department  8 non-null      object
 5   income      8 non-null      int64
 6   country     8 non-null      object
 7   city        8 non-null      object
dtypes: float64(3), int64(1), object(4)
memory usage: 644.0+ bytes

In [145]:
df['Age'] = df['Age'].astype(int)

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        8 non-null      object
 1   Age         8 non-null      int32
 2   weight      8 non-null      float64
 3   height      8 non-null      float64
 4   Department  8 non-null      object
 5   income      8 non-null      int64
 6   country     8 non-null      object
 7   city        8 non-null      object
dtypes: float64(2), int32(1), int64(1), object(4)
memory usage: 612.0+ bytes

In [147]:
df = df.convert_dtypes()
df

,name,Age,weight,height,Department,income,country,city
0,Salman,27,16.0,14.0,Information Technology,4000,India,Indore
1,Arbaz,45,27.333333,19.0,Sales,5000,USA,Los Angeles
2,Sohail,12,9.0,27.333333,Human Resource,6000,China,Wuhan
3,Neil,27,18.0,12.0,Healthcare,70000,India,Banglore
4,SUbham,25,75.0,64.0,Sales,7000,China,Bijing
5,Sakshi,27,80.0,27.333333,Automotive,7000,Japan,Tokyo
6,roahan,25,27.333333,64.0,Human Resource,9000,India,Indore
7,priyashu,30,60.0,64.0,Information Technology,10000,Shrilanka,Colambo

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        8 non-null      string
 1   Age         8 non-null      Int32
 2   weight      8 non-null      Float64
 3   height      8 non-null      Float64
 4   Department  8 non-null      string
 5   income      8 non-null      Int64
 6   country     8 non-null      string
 7   city        8 non-null      string
dtypes: Float64(2), Int32(1), Int64(1), string(4)
memory usage: 644.0 bytes

### file reading and saving

In [149]:
df

,name,Age,weight,height,Department,income,country,city
0,Salman,27,16.0,14.0,Information Technology,4000,India,Indore
1,Arbaz,45,27.333333,19.0,Sales,5000,USA,Los Angeles
2,Sohail,12,9.0,27.333333,Human Resource,6000,China,Wuhan
3,Neil,27,18.0,12.0,Healthcare,70000,India,Banglore
4,SUbham,25,75.0,64.0,Sales,7000,China,Bijing
5,Sakshi,27,80.0,27.333333,Automotive,7000,Japan,Tokyo
6,roahan,25,27.333333,64.0,Human Resource,9000,India,Indore
7,priyashu,30,60.0,64.0,Information Technology,10000,Shrilanka,Colambo

In [150]:
df.to_csv("Mydataframe.csv")

In [151]:
df.to_excel("Mydataframe1.xlsx")

In [152]:
df.to_json("Mydataframe2.json")

### Reading file from external sources

In [153]:
data = pd.read_excel(r'E:\DebugShala\Python\batch1\Python libraries\Pandas\Unicorn_Companies.xlsx')

In [154]:
data

,index,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding,Select Investors
0,0,Bytedance,180000000000,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,8000000000,"Sequoia Capital China, SIG Asia Investments, S..."
1,1,SpaceX,100000000000,2012-12-01,Other,Hawthorne,United States,North America,2002,7000000000,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,2,SHEIN,100000000000,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2000000000,"Tiger Global Management, Sequoia Capital China..."
3,3,Stripe,95000000000,2014-01-23,Fintech,San Francisco,United States,North America,2010,2000000000,"Khosla Ventures, LowercaseCapital, capitalG"
4,4,Klarna,46000000000,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,4000000000,"Institutional Venture Partners, Sequoia Capita..."
...,...,...,...,...,...,...,...,...,...,...,...
1052,1069,Zhaogang,1000000000,2017-06-29,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379000000,"K2 Ventures, Matrix Partners China, IDG Capital"
1053,1070,Zhuan Zhuan,1000000000,2017-04-18,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990000000,"58.com, Tencent Holdings"
1054,1071,Zihaiguo,1000000000,2021-05-06,Consumer & retail,Chongqing,China,Asia,2018,80000000,"Xingwang Investment Management, China Capital ..."
1055,1072,Zopa,1000000000,2021-10-19,Fintech,London,United Kingdom,Europe,2005,792000000,"IAG Capital Partners, Augmentum Fintech, North..."
1056,1073,Zwift,1000000000,2020-09-16,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620000000,"Novator Partners, True, Causeway Media Partners"

In [155]:
data.head()

,index,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding,Select Investors
0,0,Bytedance,180000000000,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,8000000000,"Sequoia Capital China, SIG Asia Investments, S..."
1,1,SpaceX,100000000000,2012-12-01,Other,Hawthorne,United States,North America,2002,7000000000,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,2,SHEIN,100000000000,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2000000000,"Tiger Global Management, Sequoia Capital China..."
3,3,Stripe,95000000000,2014-01-23,Fintech,San Francisco,United States,North America,2010,2000000000,"Khosla Ventures, LowercaseCapital, capitalG"
4,4,Klarna,46000000000,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,4000000000,"Institutional Venture Partners, Sequoia Capita..."

In [156]:
data.tail()

,index,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding,Select Investors
1052,1069,Zhaogang,1000000000,2017-06-29,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379000000,"K2 Ventures, Matrix Partners China, IDG Capital"
1053,1070,Zhuan Zhuan,1000000000,2017-04-18,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990000000,"58.com, Tencent Holdings"
1054,1071,Zihaiguo,1000000000,2021-05-06,Consumer & retail,Chongqing,China,Asia,2018,80000000,"Xingwang Investment Management, China Capital ..."
1055,1072,Zopa,1000000000,2021-10-19,Fintech,London,United Kingdom,Europe,2005,792000000,"IAG Capital Partners, Augmentum Fintech, North..."
1056,1073,Zwift,1000000000,2020-09-16,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620000000,"Novator Partners, True, Causeway Media Partners"

In [157]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1057 entries, 0 to 1056
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             1057 non-null   int64
 1   Company           1057 non-null   object
 2   Valuation         1057 non-null   int64
 3   Date Joined       1057 non-null   datetime64[ns]
 4   Industry          1057 non-null   object
 5   City              1057 non-null   object
 6   Country           1057 non-null   object
 7   Continent         1057 non-null   object
 8   Year Founded      1057 non-null   int64
 9   Funding           1057 non-null   int64
 10  Select Investors  1057 non-null   object
dtypes: datetime64[ns](1), int64(4), object(6)
memory usage: 91.0+ KB

In [158]:
data.describe()

,index,Valuation,Date Joined,Year Founded,Funding
count,1057.000000,1.057000e+03,1057,1057.000000,1.057000e+03
mean,534.822138,3.455061e+09,2020-05-17 09:02:12.828760832,2012.871334,5.674920e+08
min,0.000000,1.000000e+09,2007-07-02 00:00:00,1919.000000,0.000000e+00
25%,268.000000,1.000000e+09,2019-05-16 00:00:00,2011.000000,2.240000e+08
50%,534.000000,2.000000e+09,2021-03-26 00:00:00,2014.000000,3.740000e+08
75%,800.000000,3.000000e+09,2021-09-21 00:00:00,2016.000000,6.280000e+08
max,1073.000000,1.800000e+11,2022-04-05 00:00:00,2021.000000,1.400000e+10
std,309.498193,8.567033e+09,NaN,5.726277,8.201835e+08

### Dataframe merging

In [159]:
import pandas as pd
df1 = pd.DataFrame({
    'Name':['A','B','C','D'],
     'Value1':[1,2,3,4]      
})
df1

  Name  Value1
0    A       1
1    B       2
2    C       3
3    D       4

In [160]:
df2 = pd.DataFrame({
    'Name':['B','D',"E","F"],
     'Value2':[10,20,30,40]      
})
df2

  Name  Value2
0    B      10
1    D      20
2    E      30
3    F      40

In [161]:
pd.merge(df1,df2,on='Name',how='inner') # inner join or merging

  Name  Value1  Value2
0    B       2      10
1    D       4      20

In [162]:
pd.merge(df1,df2,on='Name',how='left') # left

  Name  Value1  Value2
0    A       1     NaN
1    B       2    10.0
2    C       3     NaN
3    D       4    20.0

In [163]:
pd.merge(df1,df2,on='Name',how='right') # right

  Name  Value1  Value2
0    B     2.0      10
1    D     4.0      20
2    E     NaN      30
3    F     NaN      40

In [164]:
pd.merge(df1,df2,on='Name',how='outer') # left

  Name  Value1  Value2
0    A     1.0     NaN
1    B     2.0    10.0
2    C     3.0     NaN
3    D     4.0    20.0
4    E     NaN    30.0
5    F     NaN    40.0

#### Join

In [165]:
import pandas as pd

In [166]:
df1

  Name  Value1
0    A       1
1    B       2
2    C       3
3    D       4

In [167]:
df2

  Name  Value2
0    B      10
1    D      20
2    E      30
3    F      40

In [168]:
df1.set_index('Name', inplace=True)
df2.set_index('Name', inplace=True)

In [169]:
df1

      Value1
Name
A          1
B          2
C          3
D          4

In [170]:
df2

      Value2
Name
B         10
D         20
E         30
F         40

In [171]:
inner_join = df1.join(df2, how='inner')
print(inner_join)

      Value1  Value2
Name
B          2      10
D          4      20

In [172]:
left_join = df1.join(df2)
print(left_join)

      Value1  Value2
Name
A          1     NaN
B          2    10.0
C          3     NaN
D          4    20.0

In [173]:
right_join = df1.join(df2, how='right')
print(right_join)

      Value1  Value2
Name
B        2.0      10
D        4.0      20
E        NaN      30
F        NaN      40

In [174]:
outer_join = df1.join(df2, how='outer')
print(outer_join)

      Value1  Value2
Name
A        1.0     NaN
B        2.0    10.0
C        3.0     NaN
D        4.0    20.0
E        NaN    30.0
F        NaN    40.0